services:
  game:
    build: .
    environment:
      - PORT=${PORT:-80}
    ports:
      - "${PORT:-80}:${PORT:-80}"
    volumes:
      - levels-data:/app/src/server
    restart: unless-stopped

volumes:
  levels-data:
