import { Images } from './images';
import { ObjectType, Who } from './types';
import { Player } from './player';
import { BaseCSW } from './base/baseCsw';
export declare class BTankManager {
    playerInstance: Player;
    playerImages: Images[];
    cswArr: BaseCSW[];
    ghosts: BaseCSW[];
    bulletsArr: any[];
    delayedPics: any[];
    drawContext: any;
    infoContext: any;
    againBtn: any;
    gameOverBlock: any;
    crashImages: any[];
    backgroundImage: any;
    counterImages: any;
    cswAI: any;
    delayedPic: any;
    gameInfo: HTMLElement;
    titleBlock: any;
    gameFieldBlock: HTMLElement;
    cpuImages: {};
    crashImage: any[];
    blackbackgroundImage: any;
    obstacleImage: any;
    borderImage: any;
    spaceBrickImages: any[];
    gameCam: any;
    constructor(cswAI: any);
    init(): Promise<any[]>;
    placeBorders(): void;
    pushNewObject(obj: any, ghost: any): void;
    getGameCam(): any;
    createCSW(x: number, y: number, who: Who, // TODO: this field should be in ship class (csw or cswai or obstacle)
    delay: number, typeParam: ObjectType, ghost: boolean, wayPoints: number[]): Player;
    checkCSWWithPixelPrecision(x: any, y: any, whoAsks: any): boolean;
    getShipDimensions(direction: any, iam: any, type: any): {
        width: number;
        height: number;
    };
    checkIfTwoShipsCross(nx: any, ny: any, whoAsks: any, typeToCheckParam: any): BaseCSW;
    getBulletWithPixelPrecision(x: any, y: any, parentShip: any, bulletInst: any): any;
    getCSWWithPixelPrecision(x: any, y: any, whoAsks: any): BaseCSW;
    getAllGhosts(): BaseCSW[];
    getAllShips(): BaseCSW[];
    getAllBullets(): any[];
    addShip(ship: any): void;
    createDelayedPic(x: any, y: any): void;
    removeDelayedPic(dpObj: any): void;
    getAllDelayedPics(): any[];
    removeBullet(bullet: any): void;
    removeShip(ship: any): void;
    destroyAll(): void;
    drawcswmt9(x: any, y: any, d: any): void;
    drawcswmt9ghost(x: any, y: any, d: any): void;
    drawcswmt5(x: any, y: any, d: any): void;
    drawObstacle(x: any, y: any): void;
    drawBorder(x: any, y: any): void;
    drawStaticShip(x: any, y: any): void;
    drawSpaceBrick(x: any, y: any, n: any): void;
    drawWayPoint(x: any, y: any, n: any): void;
    drawCounter(x: any, y: any, n: any): void;
    DrawCrash(x: any, y: any, frameCounter: any): void;
    drawBackground(): void;
    showLogo(): void;
    showNames(): void;
    showGameOver(): void;
    showWin(): void;
    displayLifeBar(player: any): void;
}
