import { BTankManager } from './btank';
import { Bullet } from './bullet';
import { Direction, PathUnit, Who } from './types';
declare const CSWAI_0: {
    new (): {
        pathPresetCount: number;
        AI_generateNewPath(): PathUnit;
        AI_update(timestamp: number): void;
        CPU_BULLETS_INTERVAL: number;
        fireStartTime: number;
        pathUnit: PathUnit;
        pathStartTime: number;
        pathsPresets: PathUnit[];
        fire(timestamp: number): void;
        draw(): void;
        hitByBullet(bulletInstance: Bullet): void;
        plusShapedScan(distance: number): Direction;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        init(mx: number, my: number, who: Who, BTankInst: any): void;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare const CSWAI_1: {
    new (): {
        fireLastTime: number;
        newFireTime: number;
        disableAI: boolean;
        msCount: number;
        msArray: number[];
        accels: number[];
        dirs: number[];
        init(mx: number, my: number, who: Who, BTankInst: BTankManager): void;
        AI_generateNewPath(): {
            d: Direction;
            accel: number;
            ms: number;
        };
        AI_generateNewFireTime(): number;
        update(timestamp: number): void;
        CPU_BULLETS_INTERVAL: number;
        fireStartTime: number;
        pathUnit: PathUnit;
        pathStartTime: number;
        pathsPresets: PathUnit[];
        fire(timestamp: number): void;
        draw(): void;
        hitByBullet(bulletInstance: Bullet): void;
        plusShapedScan(distance: number): Direction;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare type Wp = number[];
declare const CSWAI_customPaths: {
    new (): {
        wpCounter: number;
        wpStartTime: number;
        currentWp: Wp;
        wayPoints: Wp[];
        init(mx: number, my: number, who: Who, BTankInst: BTankManager, wayPoints?: Wp[]): void;
        update(timestamp: number): void;
        CPU_BULLETS_INTERVAL: number;
        fireStartTime: number;
        pathUnit: PathUnit;
        pathStartTime: number;
        pathsPresets: PathUnit[];
        fire(timestamp: number): void;
        draw(): void;
        hitByBullet(bulletInstance: Bullet): void;
        plusShapedScan(distance: number): Direction;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare const Obstacle: {
    new (): {
        draw(): void;
        hitByBullet(): void;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        init(mx: number, my: number, who: Who, BTankInst: any): void;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare const Border: {
    new (): {
        draw(): void;
        hitByBullet(): void;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        init(mx: number, my: number, who: Who, BTankInst: any): void;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare const StaticShip: {
    new (): {
        init(mx: number, my: number, who: Who, BTankInst: BTankManager): void;
        draw(): void;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        hitByBullet(bulletInstance: Bullet): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
declare const SpaceBrick: {
    new (): {
        init(mx: number, my: number, who: Who, BTankInst: BTankManager): void;
        draw(): void;
        hitByBullet(_bulletInstance: Bullet): void;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("./types").Dimensions;
        BTankInst: any;
        iam: Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
export { CSWAI_0, CSWAI_1, CSWAI_customPaths, Border, SpaceBrick, StaticShip, Obstacle };
