import { Bullet } from '../bullet';
import { Direction, PathUnit } from '../types';
export declare const BaseCPU: {
    new (): {
        CPU_BULLETS_INTERVAL: number;
        fireStartTime: number;
        pathUnit: PathUnit;
        pathStartTime: number;
        pathsPresets: PathUnit[];
        fire(timestamp: number): void;
        draw(): void;
        hitByBullet(bulletInstance: Bullet): void;
        plusShapedScan(distance: number): number;
        lastBulletTimeStamp: number;
        CSWSPEED: number;
        inertiaDirections: {
            0: number;
            1: number;
            2: number;
            3: number;
        };
        inertiaTimerIsRunning: boolean;
        d: Direction;
        stopAccel: boolean;
        MAXIMUM_ACCELERATION: number;
        dimensions: import("../types").Dimensions;
        BTankInst: any;
        iam: import("../types").Who;
        maxlife: number;
        life: number;
        bulletsAmountOnFire: number;
        x: number;
        y: number;
        type: any;
        init(mx: number, my: number, who: import("../types").Who, BTankInst: any): void;
        createNewBullet(startX: number, startY: number, startD: Direction, whoFires?: import("../types").Who): void;
        setDirectionAndAccel(d: Direction, accel: number, ms: number): void;
        getDirSum(): number;
        inertia(): void;
        waitAndCall(callback: Function, ms: number): void;
        inertiaStartAttempt(): void;
        stop(): void;
        move(direction: Direction): void;
        update(timestamp: number): void;
        getVXY(d: any): {
            vx: number;
            vy: number;
        };
        getVXYAndAngle(d: any): any;
        initCoords(nx: number, ny: number, nd: any): void;
    };
};
